### ISSUE TITLE
Are there any docs?

### ISSUE THREAD

**Issue by thomas-frantz** [bencarter78/odbc#1]
Some documentation at least outlining:

> How to install
> What version of Laravel this is for
> If this is even complete

Would have been really appreciated considering this is pretty much the first package you see for "odbc" in packagist.org

I'm writing some stuff in Laravel that will require an ODBC driver for Laravel (or I'll end up writing my own or something I guess). Would you consider putting any documentation up?

Thanks

**Comment by ghost** [comment]
Hi, I've now added some documentation now so hopefully it'll be of some use to you.
