### ISSUE TITLE
Eloquent SQL Server 2000

### ISSUE THREAD

**Issue by 4ern** [bencarter78/odbc#2]
I'm using a Server with SQL Server 2000 in conjunction with laravel. I have been successfully able to connect with the TCK / ODBC.

Now I have a problem with the -> find () method, which creates a SQL string with the LIMIT statement. Unfortunately the SQL Server 2000 only knows the TOP statement.

Is there a chance to add a method or else so I could use eloquents?

Thanks

**Comment by mlntn** [comment]
@4ern I just added a pull request that fixes that. See #3.
