### ISSUE TITLE
Call to undefined method TCK\Odbc\ODBCConnection::get()

### ISSUE THREAD

**Issue by rafwell** [bencarter78/odbc#8]
I dont know why but using the sample on readme: `DB::connection('odbc')->get('TB_Item_ContratoCliente')->all()` i've get this error: Call to undefined method TCK\Odbc\ODBCConnection::get().

Using the $connection in model work fine.

**Comment by reno1979** [comment]
The documentation is not correct, try 

`DB::connection('odbc')->table('TB_Item_ContratoCliente')->get()->all();`
